version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    environment:
      - DOMAIN
    ports:
      - 80:80
    volumes:
      - ./nginx/templates/initiate:/etc/nginx/templates
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/certbot/data:/var/www/certbot
      - ./nginx/content:/usr/share/nginx/html
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    environment:
      - DOMAIN
      - EMAIL
    depends_on:
      - nginx
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot --email "${EMAIL}" --agree-tos --no-eff-email -d "${DOMAIN}"
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/certbot/data:/var/www/certbot